import Head from "next/head";
import {UserPageList} from "@/components/page/components/UserPageList";
import {useUser} from "@/components/user-authentication/hooks/useUser";
import {InitFilter} from "@/components/page/components/Preference/InitFilter";
import {EventFilterStyles, ListHeader} from "@/components/page/styles/PageFilterStyles";
import {WebsiteFilter} from "@/components/page/components/Preference/WebsiteFilter";
import {ResetPreferenceFilter} from "@/components/page/components/Preference/ResetPreferenceFilter";
import {StatusFilter} from "@/components/page/components/Preference/StatusFilter";
import {ExportPages} from "@/components/page/components/Preference/ExportPages";

export default function Home() {
    const user = useUser()

    if (!user) return null

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <>
            {(user.websitePreference !== null && user.hideComplete !== null) &&  (<>
                <ListHeader>
                    <EventFilterStyles>
                        <WebsiteFilter/>
                        <StatusFilter/>
                        <ResetPreferenceFilter/>
                        <div className="actions">
                            <ExportPages />
                        </div>
                    </EventFilterStyles>
                    <UserPageList />
                </ListHeader>
            </>)
            }
            {(user.websitePreference === null || user.hideComplete === null) &&  (<>
                <InitFilter />
            </>)
            }
        </>
    </>
  );
}
